//  ___VARIABLE_productName:identifier___ViewController.h
//
//  Generated by the the JBoss AeroGear Xcode Project Template on ___DATE___.
//  See Project's web site for more details http://www.aerogear.org
//

#import <UIKit/UIKit.h>

@interface ___VARIABLE_productName:identifier___ViewController : UITableViewController

@end