//  ___VARIABLE_classPrefix:identifier___ViewController.m
//
//  Generated by the the JBoss AeroGear xCode Project Template on ___DATE___.
//  See Project's web site for more details http://www.aerogear.org
//

#import "___VARIABLE_classPrefix:identifier___ViewController.h"
#import "___PACKAGENAMEASIDENTIFIER___APIClient.h"

@implementation ___VARIABLE_classPrefix:identifier___ViewController {
    NSArray *_tasks;
}

- (void)viewDidLoad {
    [super viewDidLoad];

    // fetch the data
    [[___PACKAGENAMEASIDENTIFIER___APIClient sharedInstance].tasksPipe read:^(id responseObject) {
        _tasks = responseObject;
        
        // update table with the newly fetched data
        [self.tableView reloadData];
        
    } failure:^(NSError *error) {
        NSLog(@"An error has occured during read! \n%@", error);
    }];
}

- (void)viewDidUnload {
    [super viewDidUnload];
    // Release any retained subviews of the main view.
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation {
    return (interfaceOrientation != UIInterfaceOrientationPortraitUpsideDown);
}

- (NSInteger)tableView:(UITableView *)tableView numberOfRowsInSection:(NSInteger)section {
    return [_tasks count];
}

- (UITableViewCell *)tableView:(UITableView *)tableView cellForRowAtIndexPath:(NSIndexPath *)indexPath {
    static NSString *CellIdentifier = @"Cell";
    UITableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:CellIdentifier];
    
    if (cell == nil) {
        cell = [[UITableViewCell alloc]initWithStyle:UITableViewCellStyleDefault reuseIdentifier:CellIdentifier];
    }
    
    NSUInteger row = [indexPath row];
    
    cell.textLabel.text = [[_tasks objectAtIndex:row] objectForKey:@"title"];
    
    return cell;
}

@end