//  ___VARIABLE_classPrefix:identifier___ViewController.h
//
//  Generated by the the JBoss AeroGear xCode Project Template on ___DATE___.
//  See Project's web site for more details http://www.aerogear.org
//

#import <UIKit/UIKit.h>

@interface ___VARIABLE_classPrefix:identifier___ViewController : UITableViewController

@end